# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://maimanuel.github.io/rl-playground/"

git_url = "https://github.com/maimanuel/rl-playground/tree/master/"

def custom_doc_links(name): return None
