# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_core.ipynb (unless otherwise specified).

__all__ = ['hello', 'uniform_gravity_2d', 'Ball']

# Cell
def hello():
    print(hello)

# Cell
import numpy as np

class uniform_gravity_2d():
    def __init__(self,g=9.8):
        self.g=g
        self.a=np.array([0,-self.g])
        self.objects = []

    def time_step(self,delta_t=0.01):
        for o in self.objects:
            self.evolve(o,delta_t=delta_t)
            if o.x[1]<0:
                o.x[1]*=-1
                o.v[1]*=-0.7

    def evolve(self,o,delta_t):
        #applies evolution to position (2d array)
        o.v += self.a*delta_t
        o.x += o.v*delta_t +1./2*self.a*delta_t**2

class Ball():
    def __init__(self,x=np.array([0.,0.]),v=np.array([0.,0.])):
        self.x = x.astype(float)
        self.v = v.astype(float)